version: '3'

services:

  server:
    image: nginx:alpine
    restart: always
    depends_on:
      - web
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./public:/code/public
     - ./frontend-react/build:/frontend
    environment:
      - VIRTUAL_HOST=example.cms.garpix.com
      - LETSENCRYPT_HOST=example.cms.garpix.com

  node:
    image: node:14
    command: /frontend/build.sh
    volumes:
      - ./frontend-react:/frontend

  web:
    build: .
    command: sh -c "/code/run.sh"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./public:/code/public

  celery:
    build: .
    command: celery -A app worker --loglevel=info -B
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./public:/code/public

  postgres:
    image: postgres:13-alpine
    restart: always
    env_file:
    - .env
    volumes:
      - ./dumps:/code/dumps
      - ./data/postgresql:/var/lib/postgresql/data

  redis:
     image: redis:alpine
     ports:
        - '6379:6379'
